<?php

/**
 * This file is part of the Sandbox application.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sandbox\System\Domain\Tests\Units\Mailer\Command;

use Sandbox\Core\Domain\Tests\Units\Command\CommandTestTrait;
use Sandbox\System\Domain\Tests\Units\TestCase;

/**
 * SendEmailCommandTests class.
 *
 * Generated by TestGenerator on 2018-02-15 at 10:51:52.
 */
class SendEmailCommandTests extends TestCase
{
    use CommandTestTrait;

    /**
     * {@inheritdoc}
     */
    protected function getArguments()
    {
        return array(
            'app.user.reset_password',
            array('ivannis.suarez@gmail.com'),
            array('code' => '123'),
            array(),
        );
    }

    /**
     * {@inheritdoc}
     */
    protected function validatorProvider()
    {
        return array(
            array(
                'assert' => false,
                'arguments' => array(
                    678,
                    array('test@example.com'),
                    array('code' => '123'),
                    array(),
                ),
            ),
            array(
                'assert' => false,
                'arguments' => array(
                    'app.user.reset_password',
                    array('invalid@email'),
                    array('code' => '123'),
                    array(),
                ),
            ),
        );
    }
}
