<?php

/**
 * This file is part of the Sandbox/Application component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sandbox\Security\Application\Tests\Units\User\Command;

use Sandbox\Core\Domain\Tests\Units\Command\CommandTestTrait;
use Sandbox\Security\Application\Tests\Units\TestCase;
use Sandbox\Security\Domain\User\UserId;

/**
 * GenerateJWTCommandTests class.
 *
 * Generated by TestGenerator on 2018-04-03 at 17:28:01.
 */
class GenerateJWTCommandTests extends TestCase
{
    use CommandTestTrait;

    /**
     * {@inheritdoc}
     */
    public function getArguments()
    {
        return [
            UserId::next()->toNative(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function validatorProvider()
    {
        return [
            [
                'assert' => false,
                'arguments' => [
                    '',
                ],
            ],
            [
                'assert' => false,
                'arguments' => [
                    null,
                ],
            ],
        ];
    }
}
