<?php


/**
 * This file is part of the Sandbox application.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sandbox\System\Domain\Tests\Units\Mailer;

use Sandbox\System\Domain\Mailer\Command\SendEmailCommand;
use Sandbox\System\Domain\Mailer\Event\EmailWasSent;
use Sandbox\System\Domain\Tests\Units\TestCase;

/**
 * EmailCommandHandlerTests class.
 *
 * Generated by TestGenerator on 2018-02-15 at 10:51:52.
 */
class EmailCommandHandlerTests extends TestCase
{
    /**
     * Test SendEmail method.
     */
    public function testSendEmail()
    {
        $this
            ->given(
                $command = new SendEmailCommand(
                    'app.user.reset_password',
                    array('ivannis.suarez@gmail.com'),
                    array('foo' => 'bar'),
                    array()
                )
            )
            ->and($emailWasSent = null)
            ->and(
                $this->eventBus()->addListener(
                    EmailWasSent::class,
                    function (EmailWasSent $event) use (&$emailWasSent) {
                        $emailWasSent = $event;
                    },
                    100
                )
            )
            ->when($this->commandBus()->dispatch($command))
            ->then()
                ->object($emailWasSent)
                    ->isInstanceOf(EmailWasSent::class)
                ->string($emailWasSent->code()->toNative())
                    ->isEqualTo('app.user.reset_password')
                ->string($emailWasSent->senderName()->toNative())
                    ->isEqualTo('Company Name')
                ->string($emailWasSent->senderAddress()->toNative())
                    ->isEqualTo('test@example.com')
                ->array($emailWasSent->recipients())
                    ->isEqualTo(array('ivannis.suarez@gmail.com'))
        ;
    }
}
