<?php

/**
 * This file is part of the Sandbox application.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sandbox\System\Domain\Tests\Units\Mailer;

use Sandbox\System\Domain\Mailer\Email;
use Sandbox\System\Domain\Tests\Units\TestCase;
use Cubiche\Domain\System\StringLiteral;
use Cubiche\Domain\Web\EmailAddress;

/**
 * EmailTests class.
 *
 * Generated by TestGenerator on 2018-02-15 at 10:51:52.
 */
class EmailTests extends TestCase
{
    /**
     * @return Email
     */
    protected function createEmail()
    {
        return new Email(
            StringLiteral::fromNative('app.user.reset_password'),
            StringLiteral::fromNative('Company Name'),
            EmailAddress::fromNative('test@example.com'),
            StringLiteral::fromNative('Reset password'),
            StringLiteral::fromNative('Just click the button below to finish resetting your password.'),
            StringLiteral::fromNative('Mailer/User/resetPassword.html.twig')
        );
    }

    /**
     * Test Code method.
     */
    public function testCode()
    {
        $this
            ->given($email = $this->createEmail())
            ->then()
                ->string($email->code()->toNative())
                    ->isEqualTo('app.user.reset_password')
        ;
    }

    /**
     * Test Subject method.
     */
    public function testSubject()
    {
        $this
            ->given($email = $this->createEmail())
            ->then()
                ->string($email->subject()->toNative())
                    ->isEqualTo('Reset password')
        ;
    }

    /**
     * Test Content method.
     */
    public function testContent()
    {
        $this
            ->given($email = $this->createEmail())
            ->then()
                ->string($email->content()->toNative())
                    ->isEqualTo('Just click the button below to finish resetting your password.')
        ;
    }

    /**
     * Test Template method.
     */
    public function testTemplate()
    {
        $this
            ->given($email = $this->createEmail())
            ->then()
                ->string($email->template()->toNative())
                    ->isEqualTo('Mailer/User/resetPassword.html.twig')
        ;
    }

    /**
     * Test SenderName method.
     */
    public function testSenderName()
    {
        $this
            ->given($email = $this->createEmail())
            ->then()
                ->string($email->senderName()->toNative())
                    ->isEqualTo('Company Name')
        ;
    }

    /**
     * Test SenderAddress method.
     */
    public function testSenderAddress()
    {
        $this
            ->given($email = $this->createEmail())
            ->then()
                ->string($email->senderAddress()->toNative())
                    ->isEqualTo('test@example.com')
        ;
    }

    /**
     * Test enabled/disable method.
     */
    public function testIsEnabled()
    {
        $this
            ->given($email = $this->createEmail())
            ->then()
                ->boolean($email->isEnabled())
                    ->isTrue()
                ->and()
                ->when($email->disable())
                    ->boolean($email->isEnabled())
                        ->isFalse()
                    ->and()
                    ->when($email->enable())
                        ->boolean($email->isEnabled())
                            ->isTrue()
        ;
    }
}
