<?php

/**
 * This file is part of the Sandbox application.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sandbox\Core\Domain\Tests\Units;

use Cubiche\Core\Bus\Middlewares\Validator\ValidatorMiddleware;
use Cubiche\Core\Cqrs\Query\QueryBus;

/**
 * SettingQueryBus trait.
 *
 * Generated by TestGenerator on 2017-09-13 at 12:50:27.
 */
trait SettingQueryBusTrait
{
    /**
     * @var QueryBus
     */
    protected $queryBus;

    /**
     * @return QueryBus
     */
    public function queryBus()
    {
        if ($this->queryBus === null) {
            $this->queryBus = QueryBus::create();

            foreach ($this->queryHandlers() as $queryName => $queryHandler) {
                $this->queryBus->addHandler($queryName, $queryHandler);
            }

            $validatorMiddleware = null;
            foreach ($this->queryBus->middlewares() as $priority => $middlewares) {
                foreach ($middlewares as $middleware) {
                    if ($middleware instanceof ValidatorMiddleware) {
                        $validatorMiddleware = $middleware;
                        break;
                    }
                }
            }

            if ($validatorMiddleware) {
                foreach ($this->queryValidatorHandlers() as $queryName => $queryValidatorHandler) {
                    $validatorMiddleware->resolver()->addHandler($queryName, $queryValidatorHandler);
                }
            }
        }

        return $this->queryBus;
    }

    /**
     * @return array
     */
    abstract protected function queryHandlers();

    /**
     * @return array
     */
    abstract protected function queryValidatorHandlers();
}
