<?php

/**
 * This file is part of the Sandbox application.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sandbox\Core\Domain\Tests\Units;

use Cubiche\Domain\EventPublisher\DomainEventSubscriberInterface;

/**
 * SettingProjector trait.
 *
 * Generated by TestGenerator on 2017-09-13 at 12:50:27.
 */
trait SettingProjectorTrait
{
    use SettingEventDispatcherTrait;

    /**
     * Register projector as an event subscriber.
     *
     * @param DomainEventSubscriberInterface $projector
     */
    protected function registerProjector(DomainEventSubscriberInterface $projector)
    {
        $this->eventDispatcher()->addSubscriber($projector);
    }
}
