Sandbox\Security\Application\User\ReadModel\Controller\UserController:
    permissions: []
    methods:
        findAllAction: [app.user.list]
        findOneByPasswordResetTokenAction: [app.open]
        findOneByIdAction: [app.open]