<?php

/**
 * This file is part of the Sandbox application.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sandbox\Core\Application\Tests\Units\Controller;

use Sandbox\Core\Application\Controller\CommandController;
use Sandbox\Core\Application\Tests\Units\TestCase;
use Cubiche\Core\Cqrs\Command\CommandBus;

/**
 * CommandControllerTestCase class.
 *
 * Generated by TestGenerator on 2017-09-13 at 12:50:27.
 */
abstract class CommandControllerTestCase extends TestCase
{
    /**
     * @return CommandController
     */
    abstract protected function createController();

    /**
     * Test CommandBus method.
     */
    public function testCommandBus()
    {
        $this
            ->given($controller = $this->createController())
            ->then()
                ->object($controller->commandBus())
                    ->isInstanceOf(CommandBus::class)
        ;
    }
}
