<?php

/**
 * This file is part of the Sandbox application.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sandbox\Core\Application\Tests\Units\Controller;

use Sandbox\Core\Application\Controller\QueryController;
use Sandbox\Core\Application\Tests\Units\TestCase;
use Cubiche\Core\Cqrs\Query\QueryBus;

/**
 * QueryControllerTestCase class.
 *
 * Generated by TestGenerator on 2017-09-13 at 12:50:27.
 */
abstract class QueryControllerTestCase extends TestCase
{
    /**
     * @return QueryController
     */
    abstract protected function createController();

    /**
     * Test QueryBus method.
     */
    public function testQueryBus()
    {
        $this
            ->given($controller = $this->createController())
            ->then()
                ->object($controller->queryBus())
                    ->isInstanceOf(QueryBus::class)
        ;
    }
}
