<?php

/**
 * This file is part of the Sandbox application.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sandbox\System\Domain\Tests\Units\Language\Command;

use Sandbox\Core\Domain\Tests\Units\Command\CommandTestTrait;
use Sandbox\System\Domain\Language\LanguageId;
use Sandbox\System\Domain\Tests\Units\TestCase;
use Cubiche\Domain\Locale\LanguageCode;

/**
 * CreateLanguageCommandTests class.
 *
 * Generated by TestGenerator on 2018-01-25 at 17:26:00.
 */
class CreateLanguageCommandTests extends TestCase
{
    use CommandTestTrait;

    /**
     * {@inheritdoc}
     */
    protected function getArguments()
    {
        return array(
            LanguageId::next()->toNative(),
            LanguageCode::EN,
            array('en_US' => 'English', 'es_ES' => 'Ingles'),
        );
    }

    /**
     * {@inheritdoc}
     */
    protected function validatorProvider()
    {
        return array(
            array(
                'assert' => false,
                'arguments' => array(
                    '123',
                    LanguageCode::EN,
                    array('en_US' => 'English', 'es_ES' => 'Ingles'),
                ),
            ),
            array(
                'assert' => false,
                'arguments' => array(
                    '123',
                    'foo',
                    array('en_US' => 'English', 'es_ES' => 'Ingles'),
                ),
            ),
            array(
                'assert' => false,
                'arguments' => array(
                    LanguageId::next()->toNative(),
                    LanguageCode::EN,
                    array('English', 'Ingles'),
                ),
            ),
        );
    }
}
