<?php

/**
 * This file is part of the Sandbox/Application component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sandbox\Security\Application\Tests\Units\User\ProcessManager;

use Sandbox\Security\Application\Tests\Units\TestCase;
use Cubiche\Domain\EventSourcing\ReadModelInterface;

/**
 * UserRegisterProcessStateTests class.
 *
 * Generated by TestGenerator on 2018-04-03 at 17:28:01.
 */
class UserRegisterProcessStateTests extends TestCase
{
    /**
     * Test class.
     */
    public function testClass()
    {
        $this
            ->testedClass
                ->implements(ReadModelInterface::class)
        ;
    }
}
