<?php

/**
 * This file is part of the Sandbox/Application component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sandbox\System\Application\Tests\Units;

use Sandbox\System\Domain\Tests\Units\TestCase as BaseTestCase;

/**
 * TestCase class.
 *
 * Generated by TestGenerator on 2018-01-25 at 19:27:41.
 */
abstract class TestCase extends BaseTestCase
{
}
