<?php

/**
 * This file is part of the Sandbox application.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sandbox\Security\Domain\Tests\Units\User\Service;

use Sandbox\Security\Domain\Tests\Units\TestCase;
use Sandbox\Security\Domain\User\Service\TokenGenerator;

/**
 * TokenGeneratorTests class.
 *
 * Generated by TestGenerator on 2018-04-04 at 11:21:39.
 */
class TokenGeneratorTests extends TestCase
{
    /**
     * Test Generate method.
     */
    public function testGenerate()
    {
        $this
            ->given($tokenGenerator = new TokenGenerator())
            ->and($tokenGenerator2 = new TokenGenerator(123))
            ->then()
                ->string($tokenGenerator->generate())
                    ->isNotEqualTo($tokenGenerator2->generate())
        ;
    }
}
